ezsystems/ezplatform-user

src/bundle/Resources/config/services/user_settings.yml, src/lib/UserSetting/UserSetting.php, src/lib/UserSetting/UserSettingArrayAccessor.php
> JIRA: https://jira.ez.no/browse/EZP-30224
It exposes `UserSettingArrayAccessor` which can be used to access User Settings in array-like fashion. This is solely to provide BC compatibility in AdminUI `ez_user_settings` Twig global variable which is an array.
=> EZP-30224: Make `ez_user_settings` twig global load user settings dynamically

src/bundle/Resources/config/services.yml, src/lib/Templating/Twig/DateTimeExtension.php
| Tickets       | [EZP-30099](https://jira.ez.no/browse/EZP-30099)
| Tests pass?   | ?
Follow up for the https://github.com/ezsystems/ezplatform-user/pull/11. Too early access to the `language`  preference might cause https://travis-ci.org/ezsystems/ezplatform-admin-ui/jobs/502193197.
=> EZP-30099: Lazy initialize date formatters in \EzSystems\EzPlatformUser\Templating\Twig\DateTimeExtension

src/bundle/DependencyInjection/EzPlatformUserExtension.php
> JIRA: -
Added configuration for the `jms_translation` extension. Thanks to this translations could be easily extracted via:
```bash
php bin/console translation:extract -c ezplatform_user
```
=> Added configuration for the jms_translation extension

src/bundle/DependencyInjection/Compiler/UserSetting/ValueDefinitionPass.php, src/bundle/Resources/config/services/user_settings.yml, src/lib/UserSetting/ValueDefinitionRegistry.php, src/lib/UserSetting/ValueDefinitionRegistryEntry.php
| Tickets       | [EZP-30253](https://jira.ez.no/browse/EZP-30253)
| Tests pass?   | -
Added support for prioritization in the `\EzSystems\EzPlatformUser\UserSetting\ValueDefinitionRegistry` to be able to define proper order of user preferences.
=> EZP-30253: Reorder the "My Preferences" options under User settings

src/bundle/Controller/UserSettingsController.php, src/bundle/DependencyInjection/Compiler/UserSetting/ViewBuilderRegistryPass.php, src/bundle/DependencyInjection/Configuration/Parser/UserSettingsUpdateView.php, src/bundle/EzPlatformUserBundle.php, src/bundle/Resources/config/ezplatform_default_settings.yml, src/bundle/Resources/config/services.yml, src/bundle/Resources/config/services/user_settings.yml, src/bundle/Resources/views/user_settings/update.html.twig, src/lib/View/UserSettings/Matcher/Identifier.php, src/lib/View/UserSettings/UpdateView.php, src/lib/View/UserSettings/UpdateViewBuilder.php, src/lib/View/UserSettings/UpdateViewProvider.php
| Tickets       |  [EZP-30251](https://jira.ez.no/browse/EZP-30251) 
Added support for matching user setting update form view based on various criteria. Example configuration:
```yml
ezpublish:
system:
admin_group:
user_settings_update_view:
full:
ezplatform_admin_ui_datetime_format:
template: '@ezdesign/user/settings/update_datetime_format.html.twig'
match:
Identifier: [full_datetime_format, short_datetime_format]
ezplatform_admin_ui:
template: '@ezdesign/user/settings/update.html.twig'
match: true
```
Ref. …
=> EZP-30251: Display the rendering of time & date when editing the Short/Long Date & Time format

src/bundle/Resources/translations/user_change_password.en.xliff, src/bundle/Resources/translations/user_settings.en.xliff, src/lib/UserSetting/Setting/Language.php
| Tickets       |  [EZP-30306](https://jira.ez.no/browse/EZP-30306) 
| New feature?  |no
| BC breaks?    |no
| Doc needed?   |no
=> EZP-30306: Translation for User Setting Language is missing.

src/bundle/Resources/translations/user_settings.en.xliff, src/lib/Form/Type/UserSettings/DateTimeFormatType.php
| Tickets       |  [EZP-30292](https://jira.ez.no/browse/EZP-30292) 
Fixes labels in the DateTimeFormat form
=> EZP-30292: Wrong label for displaying Time in User Settings

src/bundle/Resources/config/ezplatform_default_settings.yml, src/bundle/Resources/config/services/user_settings.yml
| Tickets       |  [EZP-30514](https://jira.ez.no/browse/EZP-30514) 
As a developer, I want to be able to define a custom view for the user setting update form without impl. `PrependExtensionInterface`. For example, using the following snippet in the `/app/config/ezplatform.yml`:
```yml
ezpublish:
system:
admin_group:
user_settings_update_view:
full:
custom_setting:
template: '@ezdesign/user/settings/custom_setting.html.twig'
match:
Identifier: [ custom_setting ]        
```
Right now is not possible because `ezplatform-admin-ui` is …
=> EZP-30514: Moved default configuration to dedicated ViewProvider for the user_settings_update_view

src/bundle/Resources/views/user_settings/update.html.twig
| Tickets       |  -
Fixed multiple issues in the `user_settings/update.html.twig` template which affects  non-admin site accesses:
* Non-existing `form` block in the default page layout template
* Undefined`@ezdesign/form_fields.html.twig` in standard design
* Hidden submit button
=> Fixed multiple issues in user_settings/update.html.twig template

src/lib/UserSetting/ValueDefinitionRegistry.php, tests/lib/UserSetting/ValueDefinitionRegistryTest.php
=> Value definitions passed to the ValueDefinitionRegistry constructor should be available in the registry

src/bundle/Controller/PasswordResetController.php, src/lib/Form/Data/UserPasswordResetData.php, src/lib/Form/Factory/FormFactory.php, src/lib/Form/Type/UserPasswordResetType.php
| Tickets       |  [EZP-30417](https://jira.ez.no/browse/EZP-30417) 
Displayed validation errors for the new password field - implemented ContentType validation checks in the symfony form.
This PR depends on: https://github.com/ezsystems/repository-forms/pull/288
=> EZP-30417: Display password reset form validation errors

src/lib/UserSetting/UserSettingService.php, src/lib/UserSetting/ValueDefinitionRegistry.php, tests/lib/UserSetting/UserSettingServiceTest.php, tests/lib/UserSetting/ValueDefinitionRegistryTest.php
| Tickets       |  [EZP-30552](https://jira.ez.no/browse/EZP-30552) 
| New feature?  |no
| BC breaks?    |no
| Doc needed?   |no
User settings returned by loadUserSettings was prepared from all userSettingDefinitions, not sliced ones. Also `countUserSettings()` method was returning a number of setting which was set by the current user, not all available settings.
=> EZP-30552: Fixed the User settings pagination

src/bundle/DependencyInjection/Configuration/Parser/Pagination.php, src/bundle/EzPlatformUserBundle.php, src/bundle/Resources/config/ezplatform_default_settings.yml
| Tickets       |  [EZP-30553](https://jira.ez.no/browse/EZP-30553) 
| BC breaks?    |no
| Doc needed?   |no
Related PR: https://github.com/ezsystems/ezplatform-admin-ui/pull/999
=> EZP-30553: User settings pagination limit should be different for admin_group and other siteaccesses

src/bundle/Resources/config/routing.yaml
| Tickets       | https://jira.ez.no/browse/EZP-30819
Referencing controllers with `<Bundle>:<Controller>:<Action>` syntax (aka bundle notation) is deprecated since Symfony 4.1  and generate the following log entries:
```
[2019-08-05 19:39:35] php.INFO: User Deprecated: Referencing controllers with FrameworkBundle:Redirect:redirect is deprecated since Symfony 4.1, use "Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Referencing …
```
=> EZP-30819: Removed deprecated controller references from routes definitions

.php_cs, .travis.yml, composer.json
| Tickets       | https://jira.ez.no/browse/EZP-30872
This PR:
1) adds Travis config
2) bumps php-cs-fixer to ~2.15.0, the same version we use in Kernel
3) "borrows" missing configuration for CS-fixer from https://github.com/ezsystems/ezpublish-kernel/blob/7.5/.php_cs
=> Added Travis config, upgrade php-cs-fixer

src/bundle/Resources/config/services/user_settings.yaml
| Tickets       |  [EZP-30985](https://jira.ez.no/browse/EZP-30985)
Related upgrade notes: https://github.com/symfony/symfony/blob/4.4/UPGRADE-4.4.md#dependencyinjection (2nd point)
=> Short factory syntax is deprecated in Symfony 4.4

src/lib/ConfigResolver/ConfigurableSudoRepositoryLoader.php
| Tickets       |  [EZP-31021](https://jira.ez.no/browse/EZP-31021) 
| Bug fix?      |no
=> EZP-31021: Merged repository-forms exception & command messages refactoring

src/lib/EventListener/UserPasswordChangeRightSidebarListener.php
Question      | Answer
| Tickets       | https://jira.ez.no/browse/EZP-31236
Add title to action buttons
All PR’s to this ticket:
https://github.com/ezsystems/ezplatform-matrix-fieldtype/pull/30
https://github.com/ezsystems/ezplatform-form-builder/pull/205
https://github.com/ezsystems/ezplatform-user/pull/58
https://github.com/ezsystems/ezplatform-workflow/pull/106
https://github.com/ezsystems/date-based-publisher/pull/148
https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/246
https://github.com/ezsystems/ezplatform-admin-ui/pull/1176
=> EZP-31236: Added title to action buttons

src/lib/Form/ChoiceList/Loader/AvailableLocaleChoiceLoader.php
| Tickets       |  [EZP-31496](https://jira.ez.no/browse/EZP-31496) 
=> EZP-31496: Fixed removed getLocaleBundle() method from Intl Component

src/bundle/Controller/PasswordResetController.php
| Tickets       |  [EZP-31536](https://jira.ez.no/browse/EZP-31536) 
| Tests pass?   | ?
Fixed 
```
Too few arguments to function Twig\Environment::loadTemplate(), 1 passed in /home/vagrant/master/vendor/ezsystems/ezplatform-user/src/bundle/Controller/PasswordResetController.php on line 249 and at least 2 expected
```
by replacing `\Twig\Environment::loadTemplate` by `\Twig\Environment::load`
=> EZP-31536: Fixed invalid \Twig\Environment::loadTemplate method call

src/bundle/Controller/PasswordChangeController.php, src/bundle/Controller/PasswordResetController.php, src/bundle/Resources/config/routing.yaml, src/bundle/Resources/config/services/validators.yaml, src/lib/Form/Data/UserPasswordResetData.php, src/lib/Form/Data/UserRegisterData.php, src/lib/Form/Factory/FormFactory.php, src/lib/Form/Type/UserPasswordChangeType.php, src/lib/Form/Type/UserPasswordResetType.php, src/lib/Validator/Constraints/Password.php, src/lib/Validator/Constraints/PasswordValidator.php, tests/lib/Validator/Constraint/PasswordTest.php, tests/lib/Validator/Constraint/PasswordValidatorTest.php
| Tickets       |  https://jira.ez.no/browse/EZP-31017
| BC breaks?    | yes (but not sure if it is covered by BC policy - mandatory option for FormType)
As a part of removing circular dependencies between `ezplatform-user` and `ezplatform-admin-ui` I moved validators in question into this repository.
I have also deprecated passing contentType as part of data class as it should from start be passed as form option and removed deprecated routing aliases.
https://github.com/ezsystems/ezplatform-content-forms/pull/24 …
=> EZP-31017: Added Password Validator to change password form

src/bundle/DependencyInjection/Configuration/Parser/Pagination.php, src/bundle/Resources/config/ezplatform_default_settings.yml, src/bundle/Resources/config/services/controllers.yml
| Tickets       |  [EZP-31668](https://jira.ez.no/browse/EZP-31668) 
| BC breaks?    | yes
This is counterproposition to https://github.com/ezsystems/ezplatform-user/pull/41 that fix the issue in the easiest way, as it seems those parameters are not widely used this seems to be safe change in terms of making all other pagination parameters accessible.
it is now:
```
ezpublish:
system:
default:
pagination_user: # <-- new
user_settings_limit: 10
```
instead of
```
ezpublish:
system:
default: 
pagination: # <-- old
user_settings_limit: 10
``` …
=> EZP-31668: Introduced new key for user related pagination configuration

src/bundle/Controller/PasswordResetController.php
| Tickets       |  [EZP-31691](https://jira.ez.no/browse/EZP-31691) 
This PR fixes the password reset. During merge-up from branch `1.0` to `2.0` seems conflict was resolved incorrectly. Original PR to 1.0 https://github.com/ezsystems/ezplatform-user/pull/59/files and marge-up https://github.com/ezsystems/ezplatform-user/commit/f692ef376f7162fbcbffbfbef86e093c22c96ab8.
=> EZP-31691: Fixed password reset

src/bundle/Resources/views/user_settings/list.html.twig
JIRA ref: https://jira.ez.no/browse/EZP-31941
=> EZP-31941: A row in the tables under Admin panel should have a gray background on hover over (Same as rest of the application)

.travis.yml, .travis/prepare_ezplatform.sh, behat_suites.yml, composer.json, features/browser/signIn.feature, src/bundle/Controller/PasswordResetController.php, src/bundle/DependencyInjection/Compiler/SecurityPass.php, src/bundle/DependencyInjection/EzPlatformUserExtension.php, src/bundle/EzPlatformUserBundle.php, src/bundle/Resources/config/routing.yaml, src/bundle/Resources/config/services/feature_contexts.yaml, src/bundle/Resources/translations/forgot_password.en.xliff, src/bundle/Resources/views/forgot_password/index.html.twig, src/bundle/Security/Authentication/DefaultAuthenticationFailureHandler.php, src/bundle/Type/UserForgotPasswordReason.php, tests/Behat/Context/UserSetupContext.php
| Tickets       |  [EZP-31462](https://jira.ez.no/browse/EZP-31462)
| Tests pass?   | ?
In order to handle users with unsupported hash types redirection to "Password reset" was added
=> EZP-31462: Add handling unsupported password hash type by redirection to a password reset

src/bundle/Controller/PasswordChangeController.php, src/bundle/Controller/PasswordResetController.php
| Tickets       |  [EZP-31825](https://jira.ez.no/browse/EZP-31825)
| Tests pass?   | yes/no
Related to https://github.com/ezsystems/ezplatform-kernel/pull/117
=> EZP-31825: Use "updateUserPassword" if newer ezplatform-kernel is available

src/lib/EventListener/UserMenuListener.php
| Tickets       |  [EZP-32164](https://jira.ez.no/browse/EZP-32164) 
=> EZP-32164: Removed obsolete `icon_url` property from menu items

composer.json, src/bundle/DependencyInjection/Configuration/Parser/ForgotPassword.php, src/bundle/DependencyInjection/Configuration/Parser/ResetPassword.php, src/bundle/EzPlatformUserBundle.php, tests/bundle/DependencyInjection/Configuration/Parser/ChangePasswordTest.php, tests/bundle/DependencyInjection/Configuration/Parser/ForgotPasswordTest.php, tests/bundle/DependencyInjection/Configuration/Parser/ResetPasswordTest.php
| Tickets       |  [IBX-215](https://jira.ez.no/browse/IBX-215) 
For reasons unknown, some views were lacking proper semantic configuration and were only configurable thru whole parameter name.
=> IBX-215: Added semantic configuration for password related views

src/lib/EventListener/UserMenuListener.php
| Tickets       |  [EZP-32333](https://jira.ez.no/browse/EZP-32333)
As the title states.
Required `ezplatform-admin-ui` PR: https://github.com/ezsystems/ezplatform-admin-ui/pull/1759
=> EZP-32333: Validate access for 'change password' menu item

.travis.yml, behat_suites.yml, composer.json, features/browser/signIn.feature, src/bundle/DependencyInjection/EzPlatformUserExtension.php, src/bundle/Resources/config/services/test/feature_contexts.yaml, tests/Behat/Context/UserSetupContext.php
| Tickets       |  https://issues.ibexa.co/browse/IBX-264
Requires:
https://github.com/ezsystems/BehatBundle/pull/167
https://github.com/ezsystems/ezplatform-admin-ui/pull/1658
1) Adapted tests to the new approach
2) Changed UserSetupContext so that these tests can now be run on PostgreSQL
1) Remove TMP commit before merge
=>  EZP-32175: Speedup tests
