ezsystems/ezplatform-user

- src/bundle/Resources/config/routing.yml
- src/bundle/Resources/config/services.yml
- src/lib/Form/DataMapper/UserRegisterMapper.php
- src/lib/UserSetting/FormMapperInterface.php
- src/lib/UserSetting/FormMapperRegistry.php
- src/lib/UserSetting/Setting/SubitemsLimit.php
- src/lib/UserSetting/Setting/Timezone.php
- src/lib/UserSetting/UserSettingService.php
- src/lib/UserSetting/ValueDefinitionInterface.php
- src/lib/UserSetting/ValueDefinitionRegistry.php
Changes in use of deprecated interfaces,
old routes names
and one missing badboy
> EZP-29140: Fix deprecations

- src/lib/Form/Data/UserRegisterData.php
- src/lib/Form/Type/UserRegisterType.php
>JIRA: https://jira.ez.no/browse/EZP-29104
This changes two things:
1. Creates correct path of inheritance for BC.
2. New form use new data
Look also:
https://github.com/ezsystems/repository-forms/pull/281
> EZP-29104: Create correct deprecations

- src/bundle/Controller/PasswordChangeController.php
- src/lib/View/ChangePassword/FormView.php
- src/lib/View/ChangePassword/SuccessView.php
>JIRA:  https://jira.ez.no/browse/EZP-29104
Fix wrong namespace for ChangePassword views
> EZP-29104: Fix user-bundle views

- composer.json
- src/bundle/Controller/PasswordResetController.php
- src/bundle/Controller/UserRegisterController.php
- src/lib/ConfigResolver/RegistrationContentTypeLoader.php
- src/lib/ConfigResolver/RegistrationGroupLoader.php
- src/lib/Form/Data/UserRegisterData.php
- src/lib/Form/Processor/UserRegisterFormProcessor.php
- src/lib/Form/Type/UserRegisterType.php
- src/lib/View/Register/ConfirmView.php
- src/lib/View/Register/FormView.php
> JIRA: -
Added `php-cs-fixer` to composer.json and fixed code style
>  Added php-cs-fixer to dev dependencies

- src/bundle/Resources/config/services/user_settings.yml
- src/lib/UserSetting/Setting/CharacterCounter.php
JIRA issue: https://jira.ez.no/browse/EZP-29115
User settings needed for character counter extracted to `ezplatform-user` repository.
> EZP-29115: Add characters counter for text inputs

- src/bundle/Resources/translations/ezrepoforms_user_registration.en.xliff
- src/bundle/Resources/translations/messages.en.xliff
- src/bundle/Resources/translations/pagination.en.xliff
- src/bundle/Resources/translations/user_settings.en.xliff
> Updated *.xliff files

- src/bundle/DependencyInjection/Configuration/Parser/UserPreferences.php
- src/bundle/EzPlatformUserBundle.php
- src/bundle/Resources/config/ezplatform_default_settings.yml
- src/bundle/Resources/config/services.yml
- src/bundle/Resources/config/services/forms.yml
- src/bundle/Resources/config/services/user_settings.yml
- src/bundle/Resources/translations/user_settings.en.xliff
- src/lib/Form/DataTransformer/DateTimeFormatTransformer.php
- src/lib/Form/Type/UserSettings/DateTimeFormatType.php
- src/lib/Form/Type/UserSettings/FullDateTimeFormatType.php
- src/lib/Form/Type/UserSettings/ShortDateTimeFormatType.php
- src/lib/Templating/Twig/DateTimeExtension.php
- src/lib/UserSetting/Setting/AbstractDateTimeFormat.php
- src/lib/UserSetting/Setting/CharacterCounter.php
- src/lib/UserSetting/Setting/DateTimeFormatSerializer.php
- src/lib/UserSetting/Setting/FullDateTimeFormat.php
- src/lib/UserSetting/Setting/ShortDateTimeFormat.php
- src/lib/UserSetting/Setting/Value/DateTimeFormat.php
| Tickets       | [EZP-30099](https://jira.ez.no/browse/EZP-30099)
User settings / datetime format.
>  EZP-30099: Define preferred user date format

- src/lib/Form/Type/UserSettings/DateTimeFormatType.php
- src/lib/UserSetting/Setting/AbstractDateTimeFormat.php
- src/lib/UserSetting/Setting/FullDateTimeFormat.php
- src/lib/UserSetting/Setting/ShortDateTimeFormat.php
| Tickets       | [EZP-30099](https://jira.ez.no/browse/EZP-30099)
Follow up for https://github.com/ezsystems/ezplatform-user/pull/11
> EZP-30099: Wrong label in user preferences list for full/short date format

- src/bundle/DependencyInjection/Configuration/Parser/UserPreferences.php
- src/bundle/Resources/config/ezplatform_default_settings.yml
- src/bundle/Resources/config/services/forms.yml
- src/bundle/Resources/config/services/user_settings.yml
- src/lib/Form/ChoiceList/Loader/AvailableLocaleChoiceLoader.php
- src/lib/Form/Type/UserSettings/DateTimeFormatType.php
- src/lib/UserSetting/Setting/Language.php
- tests/lib/Form/Type/ChoiceList/Loader/AvailableLocaleChoiceLoaderTest.php
> Moved Language setting to ezplatform-admin-ui to ezplatform-user

- .github/pull_request_template.md
| Tickets       |  N/A
| Tests pass?   | N/A
| Doc needed?   | N?A
Added PR template based on https://github.com/ezsystems/ezplatform-admin-ui/blob/master/.github/pull_request_template.md to make our lifes easier :wink:
> Added Pull request template

- src/bundle/Resources/config/ezplatform_default_settings.yml
jira : https://jira.ez.no/browse/EZP-30250
> EZP-30250 Change the date format dropdown option for Long Date & Time format

- src/lib/UserSetting/Setting/FullDateTimeFormat.php
- src/lib/UserSetting/Setting/ShortDateTimeFormat.php
jira: https://jira.ez.no/browse/EZP-30252
> EZP-30252: Entire selected time format not displayed under User Settings > My Preferences tab

- src/bundle/Controller/UserSettingsController.php
| Tickets       |  [EZP-30303](https://jira.ez.no/browse/EZP-30303) 
> EZP-30303: Internal Sever Error when changing Time Zone

- src/bundle/Resources/config/routing.yml
| Tickets       |  [EZP-30360](https://jira.ez.no/browse/EZP-30360)
> EZP-30360: Add additional route for user register action

- src/bundle/Controller/PasswordChangeController.php
- src/bundle/Controller/PasswordResetController.php
- src/bundle/Controller/UserSettingsController.php
- src/lib/Validator/Constraints/UserPassword.php
| Tickets       | https://jira.ez.no/browse/EZP-30400
| Bug fix?      |no
To improve developer experience this PR tries simplified using of notifications by removing translator dependency and moving them to the notificationHandler.
Depends on: 
- https://github.com/ezsystems/ezplatform-admin-ui/pull/974
> EZP-30400: Inject TranslationService into NotificationService

- src/bundle/Resources/views/user_settings/list.html.twig
| Tickets       |  N/A
This PR cleans template which lists user settings on the site.
> Fixed multiple issues in user_settings/list.html.twig template

- src/bundle/Resources/views/user_settings/update.html.twig
related to https://github.com/ezsystems/ezplatform-admin-ui/pull/980
> EZP-30473: Renaming and moving templates

- src/bundle/Controller/PasswordResetController.php
- src/bundle/Resources/views/Security/mail/forgot_user_password.html.twig
- src/bundle/Resources/views/change_password/index.html.twig
- src/bundle/Resources/views/change_password/success.html.twig
- src/bundle/Resources/views/forgot_password/index.html.twig
- src/bundle/Resources/views/forgot_password/mail/forgot_user_password.html.twig
- src/bundle/Resources/views/forgot_password/success.html.twig
- src/bundle/Resources/views/forgot_password/with_login.html.twig
- src/bundle/Resources/views/register/register_confirmation.html.twig
- src/bundle/Resources/views/reset_password/index.html.twig
- src/bundle/Resources/views/reset_password/invalid_link.html.twig
- src/bundle/Resources/views/reset_password/success.html.twig
- src/bundle/Resources/views/user-profile/change_user_password.html.twig
- src/bundle/Resources/views/user_settings/list.html.twig
- src/bundle/Resources/views/user_settings/update.html.twig
jira: https://jira.ez.no/browse/EZP-30503
related to : https://github.com/ezsystems/ezplatform-admin-ui/pull/986
> EZP-30503: Change names of parameters

- src/bundle/Controller/PasswordResetController.php
- src/bundle/Controller/UserRegisterController.php
- src/lib/EventListener/UserMenuListener.php
- src/lib/Form/DataTransformer/DateTimeFormatTransformer.php
- src/lib/Templating/Twig/DateTimeExtension.php
- src/lib/UserSetting/FormMapperInterface.php
- src/lib/UserSetting/FormMapperRegistry.php
- src/lib/UserSetting/Setting/CharacterCounter.php
- src/lib/UserSetting/Setting/DateTimeFormatSerializer.php
- src/lib/UserSetting/Setting/FullDateTimeFormat.php
- src/lib/UserSetting/Setting/Language.php
- src/lib/UserSetting/Setting/ShortDateTimeFormat.php
- src/lib/UserSetting/Setting/SubitemsLimit.php
- src/lib/UserSetting/Setting/Timezone.php
- src/lib/UserSetting/UserSettingService.php
- src/lib/UserSetting/ValueDefinitionInterface.php
- src/lib/UserSetting/ValueDefinitionRegistry.php
- src/lib/UserSetting/ValueDefinitionRegistryEntry.php
- src/lib/View/UserSettings/Matcher/Identifier.php
- src/lib/View/UserSettings/UpdateViewProvider.php
| Tickets       |  [EZP-30687](https://jira.ez.no/browse/EZP-30687) 
| BC breaks?    | yes
The second part of https://github.com/ezsystems/ezplatform-admin-ui/pull/1022.
> EZP-30687: As a Maintainer I want to deprecated code in EzSystems\EzPlatformAdminUi\UserSetting be dropped

- src/bundle/Resources/config/services/user_settings.yaml
| Tickets       |  [EZP-30880](https://jira.ez.no/browse/EZP-30880) 
| Requires | https://github.com/ezsystems/ezpublish-kernel/pull/2745
> EZP-30880: Aligned Matcher Factories services definitions with Kernel changes

- src/lib/Form/Processor/UserRegisterFormProcessor.php
| Tickets       |  [EZP-30394](https://jira.ez.no/browse/EZP-30394) 
| Doc needed?   | yes/no
> EZP-30394: Re-implemented User Field Type

- src/bundle/Controller/UserRegisterController.php
- src/bundle/Resources/config/ezplatform_default_settings.yaml
- src/bundle/Resources/config/services.yaml
- src/bundle/Resources/config/services/controllers.yaml
- src/bundle/Resources/translations/change_password.en.xliff
- src/bundle/Resources/translations/ezplatform_content_forms_user_registration.en.xliff
- src/bundle/Resources/translations/forgot_password.en.xliff
- src/bundle/Resources/translations/forms.en.xliff
- src/bundle/Resources/translations/menu.en.xliff
- src/bundle/Resources/translations/pagination.en.xliff
- src/bundle/Resources/translations/registration.en.xliff
- src/bundle/Resources/translations/reset_password.en.xliff
- src/bundle/Resources/translations/user_settings.en.xliff
- src/bundle/Resources/translations/validators.en.xliff
- src/lib/ConfigResolver/ConfigurableRegistrationContentTypeLoader.php
- src/lib/ConfigResolver/ConfigurableRegistrationGroupLoader.php
- src/lib/ConfigResolver/ConfigurableSudoRepositoryLoader.php
- src/lib/EventListener/ViewTemplatesListener.php
- src/lib/Form/Data/UserRegisterData.php
- src/lib/Form/DataMapper/UserRegisterMapper.php
- src/lib/Form/Processor/UserRegisterFormProcessor.php
- src/lib/Form/Type/UserPasswordResetType.php
- src/lib/Form/Type/UserRegisterType.php
- src/lib/Form/UserFormEvents.php
| Tickets       |  [EZP-31011](https://jira.ez.no/browse/EZP-31011) 
This PR replaces dependency on `ezsystems/repository-forms` to `ezsystems/ezplatform-content-forms`.
> EZP-31011: Update namespaces in ezplatform-user

- .php_cs
- composer.json
- src/bundle/Controller/UserRegisterController.php
| Tickets       |  [EZP-31108](https://jira.ez.no/browse/EZP-31108) 
> EZP-31108: Provided common PHP CS Fixer configuration for internal use

- src/bundle/DependencyInjection/Compiler/UserSetting/FormMapperPass.php
- src/bundle/DependencyInjection/Compiler/UserSetting/ValueDefinitionPass.php
- src/lib/Form/DataTransformer/DateTimeFormatTransformer.php
- src/lib/Form/Type/UserSettingUpdateType.php
- src/lib/Templating/Twig/DateTimeExtension.php
| Tickets       |  [EZP-31021](https://jira.ez.no/browse/EZP-31021)
| Tests pass?   | yes/no
Main PR: https://github.com/ezsystems/ezpublish-kernel/pull/2878
~- [ ] Implement tests~
~- [ ] Coding standards (`$ composer fix-cs`)~
> EZP-31021: Revised exception and command messages

- src/bundle/Resources/translations/change_password.en.xliff
- src/bundle/Resources/translations/ezplatform_content_forms_user_registration.en.xliff
- src/bundle/Resources/translations/forgot_password.en.xliff
- src/bundle/Resources/translations/forms.en.xliff
- src/bundle/Resources/translations/menu.en.xliff
- src/bundle/Resources/translations/pagination.en.xliff
- src/bundle/Resources/translations/registration.en.xliff
- src/bundle/Resources/translations/reset_password.en.xliff
- src/bundle/Resources/translations/user_settings.en.xliff
- src/bundle/Resources/translations/validators.en.xliff
- src/bundle/Resources/views/forgot_password/mail/forgot_user_password.html.twig
- src/bundle/Resources/views/forgot_password/success.html.twig
- src/bundle/Resources/views/forgot_password/with_login.html.twig
- src/bundle/Resources/views/register/register_confirmation.html.twig
- src/bundle/Resources/views/reset_password/success.html.twig
- src/lib/Form/Type/UserPasswordChangeType.php
- src/lib/Form/Type/UserPasswordResetType.php
- src/lib/Form/Type/UserSettings/DateTimeFormatType.php
- src/lib/UserSetting/Setting/CharacterCounter.php
- src/lib/UserSetting/Setting/FullDateTimeFormat.php
- src/lib/UserSetting/Setting/Language.php
- src/lib/UserSetting/Setting/ShortDateTimeFormat.php
- src/lib/UserSetting/Setting/Timezone.php
- src/lib/Validator/Constraints/UserPassword.php
| Tickets       | https://jira.ez.no/browse/EZP-31020
| Tests pass?   | yes/no
https://github.com/ezsystems/ezplatform-admin-ui/pull/1115
> EZP-31020: Revised UI labels and messages

- src/lib/Validator/Constraints/UserPasswordValidator.php
###JIRA: https://jira.ez.no/browse/EZP-31079
> EZP-31079: Replaced loadUserByCredentials witch checkUserChredentials

- src/bundle/Command/AuditUserDatabaseCommand.php
- src/bundle/Resources/config/services.yaml
| Tickets       |  [EZP-31079](https://jira.ez.no/browse/EZP-31079) 
> EZP-31079: Provided validation for email uniqueness and login pattern

- src/lib/EventListener/UserPasswordChangeRightSidebarListener.php
Jira ref: https://jira.ez.no/browse/EZP-31439
Removed tooltips form right sidebar buttons with label
> EZP-31439: Removed titles from right/left sidebar

- src/bundle/Resources/config/services.yml
- src/lib/EventListener/UserMenuListener.php
| Tickets       |  [EZP-30965](https://jira.ez.no/browse/EZP-30965) 
> EZP-30965: Fixed type error in UserMenuListener

- src/bundle/Controller/PasswordResetController.php
- src/bundle/Controller/UserSettingsController.php
- src/bundle/Resources/config/services.yaml
- src/bundle/Resources/config/services/controllers.yaml
- src/bundle/Resources/config/services/forms.yaml
- src/bundle/Resources/config/services/user_settings.yaml
- src/lib/ConfigResolver/ConfigurableRegistrationGroupLoader.php
- src/lib/EventListener/ViewTemplatesListener.php
- src/lib/Form/Type/UserSettings/FullDateTimeFormatType.php
- src/lib/Form/Type/UserSettings/ShortDateTimeFormatType.php
- src/lib/UserSetting/Setting/SubitemsLimit.php
| Tickets       |  [EZP-30543](https://jira.ez.no/browse/EZP-30543) 
> EZP-30543: Removed Dynamic Settings functionality from kernel

- src/lib/EventListener/ViewTemplatesListener.php
> fix: is_published is not available for UserUpdateView

- src/lib/EventListener/UserMenuListener.php
JIRA ref: https://jira.ez.no/browse/EZP-32078
> EZP-32078: Update icon path

- src/bundle/Command/AuditUserDatabaseCommand.php
| Tickets       |  [EZP-32259](https://jira.ez.no/browse/EZP-32259) 
Requires https://github.com/ezsystems/ezplatform-kernel/pull/153.
> EZP-32259: Replaced "ezplatform" commands namespace with "ibexa"

- src/bundle/Resources/views/user_settings/update.html.twig
| Tickets       |  [IBX-612](https://issues.ibexa.co/browse/IBX-612)
| BC breaks?    | yes
| Doc needed?   | ?
> IBX-612: As an Editor, I want to see redesigned input field in all states (with labels)

- src/bundle/Resources/views/user_settings/update.html.twig
| Tickets       |  https://issues.ibexa.co/browse/IBX-492
| Bug fix?      | yes/no
| BC breaks?    | ?
| Doc needed?   | -
> IBX-492: As an Editor, I want to see redesigned tables
